jobs:
- job: test_randoop_coverage
  pool:
    vmImage: 'ubuntu-16.04'
  container: mdernst/randoop-ubuntu-jdkany-coverage:latest
  timeoutInMinutes: 120
  steps:
  - checkout: self
    fetchDepth: 25
    # Checkout is: git clone https://github.com/rjust/defects4j.git && cd defects4j
  - bash: env | sort
    displayName: environment
  - bash: ./framework/test/test_randoop_coverage.sh
    displayName: test_randoop_coverage.sh
